version: "3.8"
services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
    working_dir: /app
    image: app:react
    container_name: iot_mieter
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: iot
    command: sh -c "npm install && npm start && node src/server.js" 

  mysql:
    image: mysql:5.7
    volumes:
      - iot-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: iot
    ports:
      - 3006:3006

volumes:
  iot-mysql-data:

  